### ISSUE TITLE
How does UE4 utilize openCl?

### ISSUE THREAD

**Issue by jobs-git** [kwonoh/OpenCL-UE4Plugin#1]
Does it help cpu in all process like Engine GUI responsiveness, viewport rendering and or shader pre rendering?

**Comment by kwonoh** [comment]
This plugin helps you to link OpenCL with your UE projects. 
It does not changes any behavior of UE, such as viewport rendering.

See [README.md](https://github.com/kwonoh/OpenCL.uplugin/blob/master/README.md) for more details.
